name: "Run workflow"

on:
  pull_request:
    branches: 
      - main


jobs:
  Info:
    name: Info job
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Print status
        run: |
          git status
          
          
      - name: Print diff
        run: |
          git diff
          
      - name: Print ls
        run: |
          ls
